#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
    methods:  [POST]
    defaults:
        _format: json

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
api_users_me:
    path: /api/me
    methods: ['GET']
    defaults:
        _controller: App\Controller\UserController::class
        _api_resource_class: App\Entity\User
        _api_item_operation_name: get_me